fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":8] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":7]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":8] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":7]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":8] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":7]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":8] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":7]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":8] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":7]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":7] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":6]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":7] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":6]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":7] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":6]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":7] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":6]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":7] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":6]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":6] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":5]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":6] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":5]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":6] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":5]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":6] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":5]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":6] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":5]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":5] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":4]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":5] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":4]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":5] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":4]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":5] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":4]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":5] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":4]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":4] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":3]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":4] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":3]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":4] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":3]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":4] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":3]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":4] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":3]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":3] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":2]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":3] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":2]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":3] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":2]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":3] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":2]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":3] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":2]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":2] replace strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":1]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":2] replace strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":1]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":2] replace strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":1]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":2] replace strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":1]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":2] replace strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":1]

fill ~~-1~~~-1~ strat:casting_table_broad_axe_head_cast ["strat:material":4,"strat:stage":1] replace strat:casting_table_broad_axe_head_cast ["strat:material":0]
fill ~~-1~~~-1~ strat:casting_table_hammer_head_cast ["strat:material":4,"strat:stage":1] replace strat:casting_table_hammer_head_cast ["strat:material":0]
fill ~~-1~~~-1~ strat:casting_table_excavator_head_cast ["strat:material":4,"strat:stage":1] replace strat:casting_table_excavator_head_cast ["strat:material":0]
fill ~~-1~~~-1~ strat:casting_table_large_sword_blade_cast ["strat:material":4,"strat:stage":1] replace strat:casting_table_large_sword_blade_cast ["strat:material":0]
fill ~~-1~~~-1~ strat:casting_table_large_plate_cast ["strat:material":4,"strat:stage":1] replace strat:casting_table_large_plate_cast ["strat:material":0]