fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":9] replace strat:casting_basin ["strat:material":12,"strat:stage":6,"strat:faucet":1]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":9] replace strat:casting_basin ["strat:material":12,"strat:stage":6]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":6,"strat:faucet":1] replace strat:casting_basin ["strat:material":12,"strat:stage":4,"strat:faucet":1]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":6,"strat:faucet":1] replace strat:casting_basin ["strat:material":12,"strat:stage":4]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":4,"strat:faucet":1] replace strat:casting_basin ["strat:material":12,"strat:stage":2,"strat:faucet":1]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":4,"strat:faucet":1] replace strat:casting_basin ["strat:material":12,"strat:stage":2]
fill ~~-1~~~-1~ strat:casting_basin ["strat:material":12,"strat:stage":2,"strat:faucet":1] replace strat:casting_basin ["strat:material":0]