fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":5,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":5,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":5,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":5,"strat:fuel":0]


fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":2] replace strat:smeltery_controller ["strat:rotation":2,"strat:activation2":6,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":3] replace strat:smeltery_controller ["strat:rotation":3,"strat:activation2":6,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":4] replace strat:smeltery_controller ["strat:rotation":4,"strat:activation2":6,"strat:fuel":0]

fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":10]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":9]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":8]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":7]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":6]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":5]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":4]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":3]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":2]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":1]
fill ~-5~~-5 ~+5~+2~+5 strat:smeltery_controller ["strat:rotation":5] replace strat:smeltery_controller ["strat:rotation":5,"strat:activation2":6,"strat:fuel":0]

function remove_liquid
function reset_faucets